grails-app/domain/mx/com/wisnet/sadwisp/seguridad/Usuario.groovy
package mx.com.wisnet.sadwisp.seguridad

import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString

@EqualsAndHashCode(includes = 'username')
@ToString(includes = 'username', includeNames = true, includePackage = false)
class Usuario implements Serializable {

    private static final long serialVersimonUID = 1

    String username
    String password
    boolean enabled = true
    boolean accountExpired
    boolean accountLocked
    boolean passwordExpired

    String nombre
    String apellidoPaterno
    String apellidoMaterno
    String email
    Date fechaAlta


    Set<Rol> getAuthorities() {
        (UsuarioRol.findAllByUsuario(this) as List<UsuarioRol>)*.rol as Set<Rol>
    }

    static constraints = {
        username(blank: false, unique: true, size: 5..20, matches: "[0-9A-Za-z_]+")
        password(blank: false, password: true)
        enabled()
        accountExpired()
        accountLocked()
        passwordExpired()
        nombre(blank: false, size: 2..100)
        apellidoPaterno(blank: false, size: 2..50)
        apellidoMaterno(nullable: true, size: 2..50)
        email(email: true, blank: false)
        fechaAlta()

    }

    static mapping = {
        password column: '`password`'
    }

    String getNombreCompleto() {
        [nombre, apellidoPaterno, apellidoMaterno ?: ''].collect {
            it.capitalize()
        }.join(' ').replaceAll("\\s+", " ").trim()
    }

    @Override
    String toString() {
        return getNombreCompleto()
    }

    Rol getRole() {
        UsuarioRol.findAllByUsuario(this).collect { it.rol }.first()
    }

    List<Rol> getRoles() {
        UsuarioRol.findAllByUsuario(this).collect { it.rol }
    }

    List<Rol> getOtherRoles() {
        def roles = Rol.list([sort:'nombre'])
        def owned = getRoles()
        roles.removeAll(owned)
        roles
    }

    boolean isOperativa() {
        enabled && !accountLocked && !accountExpired && !passwordExpired
    }

}

grails-app/controllers/mx/com/wisnet/sadwisp/seguridad/UsuarioController.groovy
package mx.com.wisnet.sadwisp.seguridad

import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

class UsuarioController {

    UsuarioService usuarioService
    def passwordEncoder
    UsuarioRolService usuarioRolService
    def springSecurityService


    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond usuarioService.list(params), model:[usuarioCount: usuarioService.count()]
    }

    def show(Long id) {
        respond usuarioService.get(id)
    }

    def create() {
        respond new Usuario(params)
    }

    def save(Usuario usuario) {
        if (usuario == null) {
            notFound()
            return
        }

        try {
            usuario.fechaAlta = new Date()
            usuario.password = encodePassword(usuario.password)
            usuarioService.save(usuario)
            // Se agregan los roles del usuario

            // Se obtienen los roles seleccionados
            def idRoles = params.list('roles')
            def roles = Rol.getAll(idRoles)

            roles.each { rol ->
                def usuarioRol = new UsuarioRol(usuario: usuario, rol: rol)
                usuarioRolService.save(usuarioRol)
            }
        } catch (ValidationException e) {
            respond usuario.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'usuario.label', default: 'Usuario'), usuario.id])
                redirect usuario
            }
            '*' { respond usuario, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond usuarioService.get(id)
    }

    def update(Usuario usuario) {
        if (usuario == null) {
            notFound()
            return
        }

        try {
            usuario.password = encodePassword(usuario.password)
            usuarioService.save(usuario)
        } catch (ValidationException e) {
            respond usuario.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'usuario.label', default: 'Usuario'), usuario.id])
                redirect usuario
            }
            '*'{ respond usuario, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        usuarioService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'usuario.label', default: 'Usuario'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'usuario.label', default: 'Usuario'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }


    private String encodePassword(String password) {
        springSecurityService?.passwordEncoder ? springSecurityService.encodePassword(password) : password
    }
}

grails-app/views/usuario/_form.gsp
<%@ page import="mx.com.wisnet.sadwisp.seguridad.Rol" %>
<div class="row">
    <hr>
    <div class="form-group col-md-4">
        <label class="control-label" for="username"><g:message code="usuario.username.label"/></label>
        <g:textField name="username" class="form-control" maxlength="50" required="" value="${usuario.username}"/>
    </div>
    <div class="form-group col-md-4">
        <label class="control-label" for="password"><g:message code="usuario.password.label"/></label>
        <g:passwordField name="password" class="form-control" maxlength="50" required="" value="${usuario.password}"/>
    </div>
    <div class="form-group col-md-4">
        <label class="control-label" for="nombre"><g:message code="usuario.nombre.label"/></label>
        <g:textField name="nombre" class="form-control" maxlength="50" required="" value="${usuario.nombre}"/>
    </div>
    <div class="form-group col-md-4">
        <label class="control-label" for="apellidoPaterno"><g:message code="usuario.apellido.paterno.label"/></label>
        <g:textField name="apellidoPaterno" class="form-control" maxlength="50" required="" value="${usuario.apellidoPaterno}"/>
    </div>
    <div class="form-group col-md-4">
        <label class="control-label" for="apellidoMaterno"><g:message code="usuario.apellido.materno.label"/></label>
        <g:textField name="apellidoMaterno" class="form-control" maxlength="50" required="" value="${usuario.apellidoMaterno}"/>
    </div>
    <div class="form-group col-md-4">
        <label class="control-label" for="email"><g:message code="usuario.email.label"/></label>
        <g:textField name="email" class="form-control" maxlength="150" required="" value="${usuario.email}"/>
    </div>
    <div class="form-group col-md-4">
        <g:select class="form-control" name="roles"
                  from="${mx.com.wisnet.sadwisp.seguridad.Rol.list()}"
                  optionKey="id"
                  optionValue="nombre"
                  multiple="true"
                  required=""/>
    </div>

</div>

grails-app/views/usuario/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="inicio" />
        <g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>

        <div id="create-usuario" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.usuario}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.usuario}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.usuario}" method="POST">

                <g:render template="form" model="[usuario:usuario]"/>

                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/usuario/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="inicio" />
        <g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>

        <div id="edit-usuario" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.usuario}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.usuario}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.usuario}" method="PUT">
                <g:hiddenField name="version" value="${this.usuario?.version}" />
                <fieldset class="form">
                    <f:all bean="usuario"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/usuario/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="inicio" />
        <g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>

    <g:link class="btn btn-primary btn-block col-sm-2 col-md-2" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link>
    <br>

    <div id="list-usuario" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>


        <table id="list-portafolios" class="table table-striped table-bordered table-condensed table-hover tablesorter">
            <thead>
            <tr>
                <th>Username</th>
                <th>Nombre</th>
                <th>Activo</th>
            </tr>
            </thead>
            <tbody>
            <g:each in="${usuarioList}" var="item">
                <tr>

                    <td>
                        <g:link action="show" id="${item.id}">
                            <g:fieldValue bean="${item}" field="username" />
                        </g:link>
                    </td>
                    <td><g:fieldValue bean="${item}" field="nombre" /></td>
                    <td><g:fieldValue bean="${item}" field="enabled" /></td>




                </tr>
            </g:each>
            </tbody>
        </table>



        <div class="pagination">
                <g:paginate total="${usuarioCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/usuario/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="inicio" />
        <g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
                <div id="show-usuario" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if><br>

                    <table class="table table-striped table-bordered table-condensed table-hover">
                        <tbody>
                        <tr>
                            <th class="span3"><g:message code="usuario.username.label" default="Usuario"/></th>
                            <td><g:fieldValue bean="${usuario}" field="username" /></td>
                        </tr>
                        <tr>
                            <th class="span3"><g:message code="usuario.nombre.label" default="Usuario"/></th>
                            <td><g:fieldValue bean="${usuario}" field="nombreCompleto" /></td>
                        </tr>
                        <tr>
                            <th class="span3"><g:message code="usuario.role.label" default="Usuario"/></th>
                            <td><g:fieldValue bean="${usuario}" field="role" /></td>
                        </tr>
                        <tr>
                            <th class="span3"><g:message code="usuario.enabled.label" default="Usuario"/></th>
                            <td><g:fieldValue bean="${usuario}" field="enabled" /></td>
                        </tr>
                        </tbody>
                    </table>

            <g:form resource="${this.usuario}" method="DELETE">
                <fieldset class="buttons">
%{--                    <g:link class="btn btn-primary" style="pointer-events: none;" action="edit" resource="${this.usuario}"><g:message code="default.button.edit.label" default="Edit" /></g:link>--}%
                    <g:link class="btn btn-primary" action="edit" resource="${this.usuario}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="btn btn-danger" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>