grails-app/controllers/mx/com/wisnet/sadwisp/EscritorioController.groovy
package mx.com.wisnet.sadwisp

import mx.com.wisnet.sadwisp.seguridad.Usuario

import java.time.LocalDate
import java.time.format.DateTimeFormatter
import java.time.temporal.TemporalAdjusters

class EscritorioController {

    def index() {

        def clientesLinea = 0
        def clientesSuspendidos = 0
        def pagosHoy = 0
        def pagosMes = 0


        clientesLinea = Cliente.findAllByStatusServicio("EN_LINEA").size()
        clientesSuspendidos = Cliente.findAllByStatusServicio("SUSPENDIDO").size()

        def pagos = Historial.findAllByFechaPago(LocalDate.now())
        pagos.each {
            def cliente = it.cliente
            pagosHoy += cliente.plan.costo
        }

        def fecha = LocalDate.now()
        def ultimoDiaMes = fecha.with(TemporalAdjusters.lastDayOfMonth())
        def primerDiaMes = fecha.with(TemporalAdjusters.firstDayOfMonth())
        def pagosM = Historial.findAllByFechaPagoBetween(primerDiaMes, ultimoDiaMes)

        pagosM.each {
            pagosMes+= it.cliente.plan.costo
        }

        def usuarios = Usuario.findAllByEnabled(true)
        def resumen = [:]

        usuarios.each {
            def totalCobros = 0
            def registros  = Historial.findAllByFechaPagoBetweenAndUsuarioCobro(primerDiaMes, ultimoDiaMes, it)
            if(!registros.isEmpty())
               registros.each {
                   totalCobros += it.cliente.plan.costo
               }
            resumen[it.nombreCompleto] = '$'+totalCobros
        }

        //calculo super básico traer todos los clientes y sumar sus paquetes

        double totalEnMes= Cliente.list().stream()
                .mapToDouble({ cliente -> cliente.plan.costo })
                .sum();

        def pagadoEnMes = pagosMes
        def porCobrarEnMes = totalEnMes-pagadoEnMes

        def clientesNuevos = ['semana1':10, 'semana2':5, 'semana3':3, 'semana4':4]

        [clientesLinea:clientesLinea, clientesSuspendidos:clientesSuspendidos, pagosHoy:pagosHoy,
            pagosMes:pagosMes, resumen: resumen, pagadoEnMes:pagadoEnMes, porCobrarEnMes:porCobrarEnMes, clientesNuevos:clientesNuevos]

    }


    def mostrarDiagrama(){

    }
}

grails-app/controllers/mx/com/wisnet/sadwisp/ReportesController.groovy
package mx.com.wisnet.sadwisp

import mx.com.wisnet.sadwisp.seguridad.Usuario

import java.text.SimpleDateFormat
import java.time.LocalDate
import java.time.format.DateTimeFormatter
import java.time.temporal.TemporalAdjusters
import java.util.stream.IntStream

class ReportesController {

    def index() {

        def usuarios =Usuario.list()
        [usuarios:usuarios]
    }

    def generarReporte(){


        LocalDate fechaInicio = new LocalDate(params.fechaInicio_year.toInteger(), params.fechaInicio_month.toInteger(),
                params.fechaInicio_day.toInteger());
        LocalDate fechaFin = new LocalDate(params.fechaFin_year.toInteger(), params.fechaFin_month.toInteger(),
                params.fechaFin_day.toInteger());
        def usuario = Usuario.get(params.usuario)

        def clientesLinea = 0
        def clientesSuspendidos = 0
        def pagosHoy = 0
        def pagosMes = 0
        def paramsQuery = [sort: "fechaPago", order: "desc"]
        def pagos = Historial.findAllByFechaPagoBetweenAndUsuarioCobro(fechaInicio, fechaFin, usuario, paramsQuery)
        def usuarios =Usuario.list()
        def sumatoria =  (pagos.stream().mapToDouble {i-> i.cantidad == null ? new Double(0) : i.cantidad}.sum())


        render view: 'index', model: [pagos:pagos, usuarios:usuarios,usuario:usuario,
                                      fechaInicio:params.fechaInicio, fechaFin:params.fechaFin, sumatoria:sumatoria]
    }
}

grails-app/views/layouts/_footer.gsp
<footer class="sticky-footer">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span>Copyright © http://wisnet.com.mx 2018 v.1.0.5 </span>
    </div>
  </div>
</footer>

  <!-- Bootstrap core JavaScript-->

  <asset:javascript src="jquery/jquery.min.js"/>
  <asset:javascript src="bo/js/bootstrap.bundle.min.js"/>

  <!-- Core plugin JavaScript-->

  <asset:javascript src="jquery-easing/jquery.easing.min.js"/>

  <!-- Page level plugin JavaScript-->

  <asset:javascript src="chart.js/Chart.min.js"/>
  <asset:javascript src="datatables/jquery.dataTables.js"/>
  <asset:javascript src="datatables/dataTables.bootstrap4.css"/>

grails-app/views/layouts/_header.gsp
%{--<div class="navbar navbar-default navbar-static-top"  role="navigation">--}%
  %{--<asset:image src="sadLogo.png" />--}%
%{--</div>--}%

<nav class="navbar navbar-expand navbar-dark bg-dark static-top">

    <a class="navbar-brand mr-1" href="index.html">SadWisp</a>



    <!-- Navbar Search -->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">

    </form>


    <!-- Navbar -->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown no-arrow mx-1">
            <g:link controller="notificacion" action="index" class="nav-link dropdown-toggle" >
                <i class="fas fa-bell fa-fw"></i>
                <span class="badge badge-danger">${mx.com.wisnet.sadwisp.Notificacion.count()}</span>
            </g:link>
        </li>



        <li class="nav-item no-arrow">
            <g:link controller='logout'>
                <span >SALIR</span></g:link>
        </li>


</ul>

</nav>

grails-app/views/layouts/_sidebar.gsp
    <ul class="nav sidebar">
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Administración</span>
        </h6>
        <g:link controller="usuario" action="index">Usuarios</g:link>
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Catalogos</span>
        </h6>
        <g:link controller="area" action="index">Areas</g:link>
        <g:link controller="tramite" action="index">Tramites</g:link>
        <g:link controller="tipoIdentificacion" action="index">Identificaciones</g:link>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Pre Registro</span>
        </h6>
        <g:link controller="defensor" action="index">Defensores</g:link>
        <g:link controller="proveedor" action="index">Proveedores</g:link>
        <g:link controller="visitaRecurrente" action="index">Recurrentes</g:link>

        %{--<h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">--}%
            %{--<span>Acceso</span>--}%
        %{--</h6>--}%
        %{--<g:link controller="controlAcceso" action="index">Accesos</g:link>--}%
    </ul>

grails-app/views/layouts/_sidebar2.gsp
<div id="wrapper">

    <!-- Sidebar -->
    <ul class="sidebar navbar-nav">

    <sec:ifAllGranted roles="ROLE_ADMINISTRADOR">
        <li class="nav-item active">
            <g:link class="nav-link" controller="usuario" action="index">
                <i class="fas fa-fw fa-user-alt"></i>
                <span>Usuarios</span>
            </g:link>
        </li>


        <li class="nav-item active">
            <g:link class="nav-link" controller="escritorio" action="index">
                <i class="fas fa-fw fa-chart-bar"></i>
                <span>Dashboard</span>
            </g:link>
        </li>


        <li class="nav-item active">
            <g:link class="nav-link" controller="configuracion" action="edit" id="1">
                <i class="fas fa-fw fa-chart-bar"></i>
                <span>Configuración</span>
            </g:link>
        </li>

        <li class="nav-item active">
            <g:link class="nav-link" controller="mikrotik" action="index">
                <i class="fas fa-fw fa-laptop"></i>
                <span>Mikrotiks</span></g:link>
        </li>

        <li class="nav-item active">
            <g:link class="nav-link" controller="plan" action="index">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Planes</span></g:link>
        </li>


        <li class="nav-item active">
            <g:link class="nav-link" controller="reportes" action="index">
                <i class="fas fa-fw fa-list-alt"></i>
                <span>Reportes (beta)</span></g:link>
        </li>


        </sec:ifAllGranted>

    <sec:ifAnyGranted roles="ROLE_ADMINISTRADOR,ROLE_COBRADOR">
        <li class="nav-item active">
            <g:link class="nav-link" controller="cliente" action="index">
                <i class="fas fa-fw fa-address-card"></i>
                <span>Clientes</span>
            </g:link>
        </li>

        <li class="nav-item active">
            <g:link class="nav-link" controller="cliente" action="clientesBloqueados">
                <i class="fas fa-fw fa-user-circle"></i>
                <span>Suspendidos</span>
            </g:link>
        </li>
    </sec:ifAnyGranted>

    <sec:ifAnyGranted roles="ROLE_ADMINISTRADOR, ROLE_TECNICO">
        <li class="nav-item active">
        <g:link class="nav-link" controller="ticket" action="index">
            <i class="fas fa-fw fa-ticket-alt"></i>
            <span>Soporte</span>
        </g:link>

        </li>
    </sec:ifAnyGranted>

    </ul>

    <div id="content-wrapper">
        <div class="container-fluid">

            <g:layoutBody/>
        </div>

        <g:render template="/layouts/footer"/>
    </div>


</div>

grails-app/views/layouts/inicio.gsp
<!doctype html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title><g:layoutTitle default="SADWISP"/></title>

    <g:layoutHead/>
    <!-- Custom styles for this template-->

    <asset:stylesheet src="sb-admin.css"/>
    <asset:stylesheet src="bo/bootstrap.css"/>
    <asset:stylesheet src="fontawesome-free/css/all.css"/>
    <asset:stylesheet src="datatables/dataTables.bootstrap4.css"/>

    <asset:javascript src="application.js"/>

    <asset:javascript src="application.css"/>
    <asset:stylesheet href="colores.css"/>


    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">

    <style>
    .nopadding {
    padding: 0 !important;
    margin: 0 !important;
    }
</style>
</head>

<body id="page-top" style="background-color: #ffffff">

<g:render template="/layouts/header"/>
<g:render template="/layouts/sidebar2"/>

<div class="container nopadding">



    <g:render template="/layouts/footer"/>



</div>
</body>
</html>

grails-app/views/layouts/main.gsp
<!doctype html>
<html lang="en" class="no-js">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <title>
        <g:layoutTitle default="Grails"/>
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <asset:link rel="icon" href="favicon.ico" type="image/x-ico" />

    <asset:stylesheet src="application.css"/>

    <g:layoutHead/>
</head>
<body>

    <div class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/#">
		    <asset:image src="grails.svg" alt="Grails Logo"/>
                </a>
            </div>
            <div class="navbar-collapse collapse" aria-expanded="false" style="height: 0.8px;">
                <ul class="nav navbar-nav navbar-right">
                    <g:pageProperty name="page.nav" />
                </ul>
            </div>
        </div>
    </div>

    <g:layoutBody/>

    <div class="footer" role="contentinfo"></div>

    <div id="spinner" class="spinner" style="display:none;">
        <g:message code="spinner.alt" default="Loading&hellip;"/>
    </div>

    <asset:javascript src="application.js"/>

</body>
</html>