grails-app/domain/mx/com/wisnet/sadwisp/Plan.groovy
package mx.com.wisnet.sadwisp


class Plan {

    String nombre
    String download
    String upload
    String uploadMedida
    String downloadMedida
    double costo
    String pcqDownload
    String pcqUpload
    String tipo
    static  belongsTo = [mikrotik:Mikrotik]
    String burstLimit
    String burstThreshold
    String burstTime
    String parent
    String localAddress
    String remoteAddress
    String tipoControlPPPOE //pude ser PCQ or SimpleQueues
    String addressList //la lista para el marcado de paquetes


    static mapping = {
        table 'tarifa'
    }


    static constraints = {
        pcqDownload nullable: true
        pcqUpload nullable: true
        download nullable: true
        upload nullable: true
        uploadMedida nullable: true
        downloadMedida nullable: true
        burstLimit nullable: true
        burstThreshold nullable: true
        burstTime nullable: true
        parent nullable: true
        localAddress nullable: true
        remoteAddress nullable: true
        tipoControlPPPOE nullable: true
        addressList nullable: true
    }


    String toString(){
        if(tipo.equals('PCQ')){
            return "$nombre ($pcqUpload / $pcqDownload)"

        }else if (tipo.equals('PPPOE PCQ')){
            return "$nombre ($addressList)"
        }else{
            return "$nombre ($download $downloadMedida / $upload $uploadMedida)"
        }

    }


}

grails-app/controllers/mx/com/wisnet/sadwisp/PlanController.groovy
package mx.com.wisnet.sadwisp

import grails.converters.JSON
import grails.validation.ValidationException
import mx.com.wisnet.sadwisp.dto.MessageSMSDTO
import mx.com.wisnet.sadwisp.util.Conexion
import org.grails.web.json.JSONArray
import org.springframework.http.HttpEntity
import org.springframework.http.HttpHeaders
import org.springframework.http.MediaType
import org.springframework.http.client.ClientHttpRequestFactory
import org.springframework.http.client.HttpComponentsClientHttpRequestFactory
import org.springframework.web.client.RestTemplate

import java.security.MessageDigest

import static org.springframework.http.HttpStatus.*

class PlanController {

    PlanService planService
    MikrotikHelperService mikrotikHelperService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)

        respond planService.list(params), model:[planCount: planService.count()]
    }

    def show(Long id) {
        respond planService.get(id)
    }

    def create() {
        def total = Plan.count()
        //println getSerialNumber("c")
        //if(total<10){
            respond new Plan(params)
        //}else{
        //    flash.message = message(code: 'lisencia.max.created.message')
        //    redirect(action: 'index')
        //}

    }

    def save(Plan plan) {
        if (plan == null) {
            notFound()
            return
        }

        try {
            planService.save(plan)
        } catch (ValidationException e) {
            respond plan.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'plan.label', default: 'Plan'), plan.id])
                redirect plan
            }
            '*' { respond plan, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond planService.get(id)
    }

    def update(Plan plan) {
        if (plan == null) {
            notFound()
            return
        }

        try {
            planService.save(plan)
        } catch (ValidationException e) {
            respond plan.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'plan.label', default: 'Plan'), plan.id])
                redirect plan
            }
            '*'{ respond plan, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        planService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'plan.label', default: 'Plan'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'plan.label', default: 'Plan'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }

    def renderPCQ(){
        println params
        def mikrotik = Mikrotik.get(params.mikrotik)
        if(params.tipo.equals('PPPOE')){
            def poolList = mikrotikHelperService.getIpPools(mikrotik)
            render template: 'PPPOE', model: [poolList:poolList]
            return
        }
        else if(params.tipo.equals("PCQ")){
            def pcqList = mikrotikHelperService.getPCQ(mikrotik)
            render template: 'pcq', model: [uploadList:pcqList, downloadList:pcqList]
            return
        }else if(params.tipo.equals('PPPOE PCQ')){
            def poolList = mikrotikHelperService.getIpPools(mikrotik)
            render template: 'PPPOEPCQ', model: [poolList:poolList]
            return
        }else if (params.tipo.equals('Hotspot')){
            def profiles = mikrotikHelperService.getProfilesHotspot(mikrotik)
            render template: 'hotspot', model: [profileList:profiles]
            return
        }
        else{
            render template: 'simpleQueue', model: []
        }

    }

    def sendMikrotik(Long id){
        def plan = planService.get(id)
        log.info "Enviando plan al mk" + plan.nombre

        def creado = false
        if(plan.tipo.equals('PPPOE')){
            creado = mikrotikHelperService.sendPlanPPPOE(plan)
        }else if(plan.tipo.equals("PPPOE PCQ")){
            creado = mikrotikHelperService.sendPlanPPPOEPCQ(plan)
        }else{
            //creado = mikrotikHelperService.sendQueue(cliente)
        }

        if (creado){
            flash.message="Se realizo la creación del plan pppoe correctamente"
            redirect(action:"show", id: plan.id)
        }else{
            flash.errorMessage = "Ha ocurrido un error intente más tarde"
            redirect(action:"show", id: plan.id)
            return
        }


    }

    public static String getSerialNumber(String drive) {
        String result = "";
        try {

            Process p = Runtime.getRuntime().exec("wmic diskdrive get serialnumber");
            BufferedReader input =
                    new BufferedReader(new InputStreamReader(p.getInputStream()));
            String line;
            while ((line = input.readLine()) != null) {
                result += line;
            }
            input.close();
        }
        catch(Exception e){
            e.printStackTrace();
        }
        return result.trim();
    }

}

grails-app/views/plan/_PPPOE.gsp
<div class="form-group col-md-4">
    <label class="control-label" for="upload"><g:message code="plan.upload.label"/></label>
    <g:textField name="upload" class="form-control" maxlength="50" required="" value="${plan?.upload}"/>
</div>
<div class="form-group col-md-4">
    <label class="control-label" for="uploadMedida"><g:message code="plan.upload.medida.label"/></label>
    <g:textField name="uploadMedida" class="form-control" maxlength="50" required="" value="${plan?.uploadMedida}"/>
</div>

<div class="form-group col-md-4">
    <label class="control-label" for="download"><g:message code="plan.download.label"/></label>
    <g:textField name="download" class="form-control" maxlength="50" required="" value="${plan?.download}"/>
</div>
<div class="form-group col-md-4">
    <label class="control-label" for="downloadMedida"><g:message code="plan.download.medida.label"/></label>
    <g:textField name="downloadMedida" class="form-control" maxlength="50" required="" value="${plan?.downloadMedida}"/>
</div>

<div class="form-group col-md-4">
    <label class="control-label" for="localAddress"><g:message code="plan.pppoe.local.adress"/></label>
    <g:textField name="localAddress" class="form-control" maxlength="50" required="" value="${plan?.localAddress}"/>
</div>


<div class="form-group col-md-4">
    <label class="control-label" for="remoteAddress"><g:message code="plan.pppoe.remote.adress"/></label>
    <g:select name="remoteAddress" class="form-control" id="remoteAddress"
              from="${poolList}"
              noSelection="${['':message(code:'plan.pcq.select.label')]}"
              required="true"

    />
</div>



grails-app/views/plan/_PPPOEPCQ.gsp
<div class="form-group col-md-4">
    <label class="control-label" for="addressList"><g:message code="plan.pppoe.adress.list"/></label>
    <g:textField name="addressList" class="form-control" maxlength="50" required="" value="${plan?.addressList}"/>
</div>

<div class="form-group col-md-4">
    <label class="control-label" for="localAddress"><g:message code="plan.pppoe.local.adress"/></label>
    <g:textField name="localAddress" class="form-control" maxlength="50" required="" value="${plan?.localAddress}"/>
</div>


<div class="form-group col-md-4">
    <label class="control-label" for="remoteAddress"><g:message code="plan.pppoe.remote.adress"/></label>
    <g:select name="remoteAddress" class="form-control" id="remoteAddress"
              from="${poolList}"
              noSelection="${['':message(code:'plan.pcq.select.label')]}"
              required="true"

    />
</div>



grails-app/views/plan/_campos.gsp
<div class="row">
    <hr>
    <div class="form-group col-md-4">
        <label class="control-label" for="nombre"><g:message code="plan.nombre.label"/></label>
        <g:textField name="nombre" class="form-control" maxlength="50" required="" value="${plan?.nombre}"/>
    </div>
    <div class="form-group col-md-4">
        <label class="control-label" for="costo"><g:message code="plan.costo.label"/></label>
        <g:textField name="costo" class="form-control" maxlength="50" required="" value="${plan?.costo}"/>
    </div>

    <div class="form-group col-md-4">
        <label class="control-label" for="mikrotik"><g:message code="cliente.mikrotik.label"/></label>
        <g:select name="mikrotik" class="form-control"
                  from="${mx.com.wisnet.sadwisp.Mikrotik.list()}"
                  optionKey="id"
                  required=""/>
    </div>

    <div class="form-group col-md-4">
        <label class="control-label" for="tipo"><g:message code="plan.tipo.label"/></label>
        <g:select name="tipo" class="form-control"
                  from="['Simple Queue','PCQ', 'PPPOE', 'PPPOE PCQ', 'Hotspot']"
                  noSelection="${['':message(code:'plan.select.tipo.label')]}"
                  onchange="onTipoSelect()"
                  required=""/>
    </div>



</div>

<div id='response' class="row"></div>

grails-app/views/plan/_hotspot.gsp

<div class="form-group col-md-4">
    <label class="control-label" for="remoteAddress"><g:message code="plan.hotspot.user.profile"/></label>
    <g:select name="remoteAddress" class="form-control" id="remoteAddress"
              from="${profileList}"
              noSelection="${['':message(code:'plan.pcq.select.label')]}"
              required="true"

    />
</div>



grails-app/views/plan/_pcq.gsp
<div class="form-group col-md-4">
    <label class="control-label" for="pcqUpload"><g:message code="plan.pcq.upload.label"/></label>
    <g:select name="pcqUpload" class="form-control" id="pcqUpload"
              from="${uploadList}"
              noSelection="${['':message(code:'plan.pcq.select.label')]}"
              required="true"

    />
</div>


<div class="form-group col-md-4">
    <label class="control-label" for="pcqDownload"><g:message code="plan.pcq.download.label"/></label>
    <g:select name="pcqDownload" class="form-control" id="pcqDownload"
              from="${downloadList}"
              noSelection="${['':message(code:'plan.pcq.select.label')]}"
              required="true"
    />
</div>

grails-app/views/plan/_simpleQueue.gsp
<div class="form-group col-md-4">
    <label class="control-label" for="upload"><g:message code="plan.upload.label"/></label>
    <g:textField name="upload" class="form-control" maxlength="50" required="" value="${plan?.upload}"/>
</div>
<div class="form-group col-md-4">
    <label class="control-label" for="uploadMedida"><g:message code="plan.upload.medida.label"/></label>
    <g:textField name="uploadMedida" class="form-control" maxlength="50" required="" value="${plan?.uploadMedida}"/>
</div>

<div class="form-group col-md-4">
    <label class="control-label" for="download"><g:message code="plan.download.label"/></label>
    <g:textField name="download" class="form-control" maxlength="50" required="" value="${plan?.download}"/>
</div>
<div class="form-group col-md-4">
    <label class="control-label" for="downloadMedida"><g:message code="plan.download.medida.label"/></label>
    <g:textField name="downloadMedida" class="form-control" maxlength="50" required="" value="${plan?.downloadMedida}"/>
</div>

<div class="form-group col-md-4">
    <label class="control-label" for="burstLimit"><g:message code="plan.burst.limit.label"/></label>
    <g:textField name="burstLimit" class="form-control" maxlength="50" required="" value="${plan?.burstLimit}"/>
</div>
<div class="form-group col-md-4">
    <label class="control-label" for="burstThreshold"><g:message code="plan.burst.threshold.label"/></label>
    <g:textField name="burstThreshold" class="form-control" maxlength="50" required="" value="${plan?.burstThreshold}"/>
</div>
<div class="form-group col-md-4">
    <label class="control-label" for="burstTime"><g:message code="plan.burst.time.label"/></label>
    <g:textField name="burstTime" class="form-control" maxlength="50" required="" value="${plan?.burstTime}"/>
</div>
<div class="form-group col-md-4">
    <label class="control-label" for="parent"><g:message code="plan.parent.label"/></label>
    <g:textField name="parent" class="form-control" maxlength="50" required="" value="${plan?.parent}"/>
</div>


grails-app/views/plan/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="inicio" />
        <g:set var="entityName" value="${message(code: 'plan.label', default: 'Plan')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>

        <div id="create-plan" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.plan}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.plan}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.plan}" method="POST">
                <fieldset class="form">
                    <g:render template="campos" model="[plan:plan]"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="btn btn-primary" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/plan/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'plan.label', default: 'Plan')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-plan" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-plan" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.plan}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.plan}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.plan}" method="PUT">
                <g:hiddenField name="version" value="${this.plan?.version}" />
                <fieldset class="form">
                    <f:all bean="plan"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/plan/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="inicio" />
        <g:set var="entityName" value="${message(code: 'plan.label', default: 'Plan')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>

        <div class="nav" role="navigation">

            <g:link class="btn btn-primary btn-block col-md-2 col-sm-2" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link>

        </div>
    <br>
        <div id="list-plan" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <br>

            <table id="list-portafolios" class="table table-striped table-bordered table-condensed table-hover tablesorter">
                <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Tipo</th>
                    <th>Costo</th>

                </tr>
                </thead>
                <tbody>
                <g:each in="${planList}" var="item">
                    <tr>

                        <td>

                            <g:link action="show" id="${item.id}">
                                ${item}
                            </g:link>
                        </td>
                        <td><g:fieldValue bean="${item}" field="tipo" /></td>
                        <td><g:fieldValue bean="${item}" field="costo" /></td>

                    </tr>
                </g:each>
                </tbody>
            </table>


            <div class="pagination">
                <g:paginate total="${planCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/plan/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="inicio" />
        <g:set var="entityName" value="${message(code: 'plan.label', default: 'Plan')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>

        <div id="show-plan" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>

            <br>
            <table class="table table-striped table-bordered table-condensed table-hover">
                <tbody>
                <tr>
                    <th class="span3"><g:message code="plan.mikrotik.label" default="Mikrotik"/></th>
                    <td><g:fieldValue bean="${plan}" field="mikrotik" /></td>
                </tr>
                <tr>
                    <th class="span3"><g:message code="plan.tipo.label" default="Plan"/></th>
                    <td><g:fieldValue bean="${plan}" field="tipo" /></td>
                </tr>
                <tr>
                    <th class="span3"><g:message code="plan.nombre.label" default="Nombre"/></th>
                    <td><g:fieldValue bean="${plan}" field="nombre" /></td>

                </tr>

                <tr>
                    <th class="span3"><g:message code="plan.costo.label" default="Costo"/></th>
                    <td><g:fieldValue bean="${plan}" field="costo" /></td>
                </tr>

                <g:if test="${plan.tipo.equals('PCQ')}">
                    <tr>
                        <th class="span3"><g:message code="plan.pcq.upload.label" default="Plan"/></th>
                        <td><g:fieldValue bean="${plan}" field="pcqUpload" /></td>
                    </tr>

                    <tr>
                        <th class="span3"><g:message code="plan.pcq.download.label" default="Plan"/></th>
                        <td><g:fieldValue bean="${plan}" field="pcqDownload" /></td>
                    </tr>
                </g:if>



                <g:if test="${plan.tipo.equals('PPPOE')}">
                        <tr>
                            <th class="span3"><g:message code="plan.pppoe.local.adress" default="Plan"/></th>
                            <td> ${plan.localAddress}</td>
                        </tr>
                        <tr>
                            <th class="span3"><g:message code="plan.pppoe.remote.adress" default="Plan"/></th>
                            <td> ${plan.remoteAddress}</td>
                        </tr>

                        <tr>
                            <th class="span3"><g:message code="plan.upload.label" default="Plan"/></th>
                            <td>${plan.upload} ${plan.uploadMedida}</td>
                        </tr>
                        <tr>
                            <th class="span3"><g:message code="plan.download.label" default="Plan"/></th>
                            <td>${plan.download} ${plan.downloadMedida}</td>
                        </tr>
                </g:if>

                <g:if test="${plan.tipo.equals('PPPOE PCQ')}">
                        <tr>
                            <th class="span3"><g:message code="plan.pppoe.local.adress" default="Plan"/></th>
                            <td> ${plan.localAddress}</td>
                        </tr>
                        <tr>
                            <th class="span3"><g:message code="plan.pppoe.remote.adress" default="Plan"/></th>
                            <td> ${plan.remoteAddress}</td>
                        </tr>
                        <tr>
                            <th class="span3"><g:message code="plan.pppoe.adress.list" default="Plan"/></th>
                            <td> ${plan.addressList}</td>
                        </tr>
                </g:if>

                <g:if test="${plan.tipo.equals('Simple Queue')}">
                    <tr>
                        <th class="span3"><g:message code="plan.burst.limit.label" default="Plan"/></th>
                        <td>${plan.burstLimit} ${plan.downloadMedida}</td>
                    </tr>
                    <tr>
                        <th class="span3"><g:message code="plan.burst.threshold.label" default="Plan"/></th>
                        <td>${plan.burstThreshold} ${plan.downloadMedida}</td>
                    </tr>

                    <tr>
                        <th class="span3"><g:message code="plan.burst.time.label" default="Plan"/></th>
                        <td>${plan.burstTime}</td>
                    </tr>
                    <tr>
                        <th class="span3"><g:message code="plan.parent.label" default="Plan"/></th>
                        <td>${plan.parent}</td>
                    </tr>
                    <tr>
                        <th class="span3"><g:message code="plan.upload.label" default="Plan"/></th>
                        <td>${plan.upload} ${plan.uploadMedida}</td>
                    </tr>
                    <tr>
                        <th class="span3"><g:message code="plan.download.label" default="Plan"/></th>
                        <td>${plan.download} ${plan.downloadMedida}</td>
                    </tr>
                </g:if>

                </tbody>
            </table>


            <g:form resource="${this.plan}" method="DELETE">
                <fieldset class="buttons">
                    <g:if test="${plan.tipo.equals('PPPOE')||plan.tipo.equals('PPPOE PCQ')}">
                        <g:link class="btn btn-success" action="sendMikrotik" resource="${this.plan}"><g:message code="cliente.new.queue" default="Enviar Mikrotik" /></g:link>
                    </g:if>
                    <g:link class="btn btn-primary" action="edit" resource="${this.plan}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="btn btn-danger" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>