grails-app/domain/mx/com/wisnet/sadwisp/Configuracion.groovy
package mx.com.wisnet.sadwisp

class Configuracion {

    Integer consecutivoNotas
    String direccionFecha
    int diasGraciaCorte
    int diasRecordatorio
    String mensajeCorte
    String mensajeRecordatorio
    String idDispositivo
    String keyDispositivo
    boolean editarNota
    boolean postPago
    String telefono
    String codigoPostal
    String direccion
    String permisoIft
    String aviso
    String nombreLogo = "FUSION.png"
    String qrCode
    String barCode
    boolean secretManual
    boolean secretUpdate
    String nombreEmpresa


    static constraints = {
        idDispositivo nullable: true
        keyDispositivo nullable: true
        direccion nullable: true
        permisoIft nullable: true
        telefono nullable: true
        codigoPostal nullable: true
        aviso nullable: true
        nombreLogo nullable: true
        secretManual nullable:true
        secretUpdate nullable:true
        qrCode nullable: true
        barCode nullable: true
        nombreEmpresa nullable: true

    }

    static mapping = {
        aviso type: 'text'
    }
}

grails-app/controllers/mx/com/wisnet/sadwisp/ConfiguracionController.groovy
package mx.com.wisnet.sadwisp

import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

class ConfiguracionController {

    ConfiguracionService configuracionService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond configuracionService.list(params), model:[configuracionCount: configuracionService.count()]
    }

    def show(Long id) {
        respond configuracionService.get(id)
    }

    def create() {
        respond new Configuracion(params)
    }

    def save(Configuracion configuracion) {
        if (configuracion == null) {
            notFound()
            return
        }



        try {
            configuracionService.save(configuracion)
        } catch (ValidationException e) {
            respond configuracion.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'configuracion.label', default: 'Configuracion'), configuracion.id])
                redirect configuracion
            }
            '*' { respond configuracion, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond configuracionService.get(id)
    }

    def update(Configuracion configuracion) {
        if (configuracion == null) {
            notFound()
            return
        }

        try {
            configuracionService.save(configuracion)
        } catch (ValidationException e) {
            respond configuracion.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'configuracion.label', default: 'Configuracion'), configuracion.id])
                redirect (action: 'edit', id:configuracion.id)
            }
            '*'{ respond configuracion, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        configuracionService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'configuracion.label', default: 'Configuracion'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'configuracion.label', default: 'Configuracion'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/configuracion/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'configuracion.label', default: 'Configuracion')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-configuracion" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-configuracion" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.configuracion}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.configuracion}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.configuracion}" method="POST">
                <fieldset class="form">
                    <f:all bean="configuracion"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/configuracion/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="inicio" />
        <g:set var="entityName" value="${message(code: 'configuracion.label', default: 'Configuracion')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>

    </head>
    <body>

        <div id="edit-configuracion" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.configuracion}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.configuracion}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.configuracion}" method="PUT">
                <g:hiddenField name="version" value="${this.configuracion?.version}" />
                <br/>

                    <div class="row">
                        <div class="col-sm-4">


                                    <div class="form-group ">
                                        <label class="control-label">Dirección Fecha</label>
                                        <input type="text" id="direccionFecha" name="direccionFecha" class="form-control" value="${configuracion.direccionFecha}" minlength="5" maxlength="20" required="" />
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label">Consecutivo Notas</label>
                                        <input type="text" id="consecutivoNotas" name="consecutivoNotas" class="form-control" value="${configuracion.consecutivoNotas}" required="" />
                                    </div>

                                    <div class="form-group ">
                                        <label class="control-label ">Días Recordatorio</label>
                                        <input type="text" id="diasRecordatorio" name="diasRecordatorio"
                                               class="form-control" value="${configuracion.diasRecordatorio}" maxlength="50" required="" />
                                    </div>

                                    <div class="form-group ">

                                        <label class="control-label">Días Gracia</label>
                                        <input type="text" id="diasGraciaCorte" name="diasGraciaCorte"
                                               class="form-control"
                                               value="${configuracion.diasGraciaCorte}" maxlength="50" required="" />
                                    </div>

                            <div class="form-group ">

                                <label class="control-label">Teléfono</label>
                                <input type="text" id="telefono" name="telefono"
                                       class="form-control"
                                       value="${configuracion.telefono}" maxlength="50" required="" />
                            </div>



                            <div class="form-group ">

                                <label class="control-label">Permiso IFT</label>
                                <input type="text" id="permisoIft" name="permisoIft"
                                       class="form-control"
                                       value="${configuracion.permisoIft}" maxlength="50" required="" />
                            </div>

                            <div class="form-group ">
                                <div class="row">
                                <div class="col-md-6">
                                <label class="control-label">Editar notas</label>
                                <g:checkBox name="editarNota" class="form-control" value="${configuracion.editarNota}" />
                                </div>
                                <div class="col-md-6">
                                <label class="control-label">Cobro post pago</label>
                                <g:checkBox name="postPago" class="form-control" value="${configuracion.postPago}" />
                                </div>
                                </div>
                            </div>


                            <div class="form-group ">
                                <div class="row">
                                    <div class="col-md-6">
                                        <label class="control-label">Secret Manual</label>
                                        <g:checkBox name="secretManual" class="form-control" value="${configuracion.secretManual}" />
                                    </div>
                                    <div class="col-md-6">
                                        <label class="control-label">Actualizar Secret</label>
                                        <g:checkBox name="secretUpdate" class="form-control" value="${configuracion.secretUpdate}" />
                                    </div>
                                </div>
                            </div>






                        </div>
                        <div class="col-md-6">

                            <div class="form-group ">

                                <label class="control-label">Dirección</label>
                                <input type="text" id="direccion" name="direccion"
                                       class="form-control"
                                       value="${configuracion.direccion}" maxlength="100" required="" />
                            </div>

                            <div class="form-group ">

                                <label class="control-label">Código Postal</label>
                                <input type="text" id="codigoPostal" name="codigoPostal"
                                       class="form-control"
                                       value="${configuracion.codigoPostal}" maxlength="5" required="" />
                            </div>



                            <div class="form-group">
                                <label class="control-label">Mensaje corte</label>
                                <textarea rows="2" cols="2" id="mensajeCorte" name="mensajeCorte"
                                          class="form-control"
                                          maxlength="100" required="">${configuracion.mensajeCorte}</textarea>
                            </div>


                        <div class="form-group">
                            <label class="control-label">Mensaje recordatorio</label>
                            <textarea rows="2" cols="2" id="mensajeRecordatorio" name="mensajeRecordatorio"
                                      class="form-control"
                                      maxlength="100" required=""> ${configuracion.mensajeRecordatorio}
                            </textarea>
                        </div>

                            <div class="form-group">
                                <label class="control-label">Avisos</label>
                                <textarea rows="2" cols="2" id="aviso" name="aviso"
                                          class="form-control"
                                          maxlength="500" required=""> ${configuracion.aviso}
                                </textarea>
                            </div>

                            <div class="form-group ">

                                <label class="control-label">ID Dispositivo</label>
                                <input type="text" id="idDispositivo" name="idDispositivo"
                                       class="form-control"
                                       value="${configuracion.idDispositivo}" maxlength="50" required="" />
                            </div>

                            <div class="form-group ">

                                <label class="control-label">Key Dispositivo </label>
                                <textarea rows="2" cols="2" id="keyDispositivo" name="keyDispositivo"
                                       class="form-control" required="" >${configuracion.keyDispositivo}</textarea>
                            </div>

                        </div>



                    </div>

                <fieldset class="buttons">
                    <input class="btn btn-primary" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
            <br>
            <br>

            <div class="col-md-10">
                <g:form controller="historial" action="generarPagos">

                    Introduzca el año para el cual se generaran los pagos:

                    <input type="text" id="year" name="year" class="col-md-2">


                    <input class="btn btn-success" type="submit" value="${message(code: 'default.button.generar.pagos.label', default: 'Generar Pagos')}" />
                </g:form>
            </div>
            <br>
            <br>
        </div>
    </body>
</html>

grails-app/views/configuracion/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'configuracion.label', default: 'Configuracion')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-configuracion" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-configuracion" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${configuracionList}" />

            <div class="pagination">
                <g:paginate total="${configuracionCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/configuracion/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="inicio" />
        <g:set var="entityName" value="${message(code: 'configuracion.label', default: 'Configuracion')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>

        <div id="show-configuracion" class="content scaffold-show" role="main">
            <h1>Parametros del Sistema</h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="configuracion" />
            <g:form resource="${this.configuracion}" method="PUT">
                <fieldset class="buttons">
                    <input class="btn btn-primary" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>